### ISSUE TITLE
Artistic Tags work on their own

### ISSUE THREAD

**Issue by BryanBoru** [TFT8/addons#12]
## Expected Behavior (required)
Get Creative is intended to only work on placed tags

## Current Behavior (required)
Once a player has spray paint, they can place an artistic tag on a wall

## Possible Solution
check creative tag related scripts

## Steps to Reproduce (for bugs)
1. get spray paint
2. approach an empty wall
3. place artistic tag

**Comment by theYoursTruly** [comment]
Works as intended. After ACE implemented custom tags, I changed the behavior (nobody uses those tags anyway :P )
