### ISSUE TITLE
AI avoids mines

### ISSUE THREAD

**Issue by BryanBoru** [TFT8/addons#14]
Regardless of what class the AI are they avoid individual mines. In cases where a mine detector is on the AI and/or they are engineers included. In testing there had to be multiple mines to make them have no option but to drive over them or leave their path in order to avoid them, then they drove over them. 
Tested in Vanilla, does not happen.

**Comment by theYoursTruly** [comment]
Which of our mods is causing that?

**Comment by theYoursTruly** [comment]
AI has been changed.
