### ISSUE TITLE
M249 Dependency on M60 

### ISSUE THREAD

**Issue by BryanBoru** [TFT8/addons#18]
Irony, the Minimi LMGs have a dependency on M60s and on loading get popups on missing textures with the MK48s. not game breaking, but an annoyance. 
Speak to me as I simply can not find a call for the referenced texture (m60e4_ti_ca.paa) in the PBO nor in the NIArms Repo.

**Comment by theYoursTruly** [comment]
They do not need M60s. Check your addon version.

**Comment by BryanBoru** [comment]
Running TFT_core, TFT_private, CBA>
https://gyazo.com/cf0d2426590a98ed510b0785e6a5eec3

**Comment by BryanBoru** [comment]
https://github.com/toadie2k/NIArms/blob/master/hlc_wp_saw/config.cpp#L8

**Comment by theYoursTruly** [comment]
Unpacked from our TFT_Core:
https://gyazo.com/92139b7e2923e744d7a8ba0c60e496f0
