### ISSUE TITLE
tft-uniforms

### ISSUE THREAD

**Issue by BryanBoru** [TFT8/addons#3]
**Description:**
- ![](https://lh4.googleusercontent.com/LH7v9X5kM0XnrHkdryD8oPmbhqWmq3uIQ-RVUWt_zzMbZH6nLmsTS6_EeyzRcxJ61K3MrSrsB0Fa-rs=w1920-h941)
Images for uniforms are blank in Inventory. backpacks work.

**Steps to reproduce:**
- put any TFT8 equipment on and then go into inventory in game.

**Where did the issue occur?**
- Virtual Arsenal

**Comment by BryanBoru** [comment]
I see "TODOLPicture" on define.hpp but I also see the images already done in UI, so I don't know if they are done and not working or incomplete.

**Comment by theYoursTruly** [comment]
Fixed with: https://github.com/TFT8/addons/commit/1eb911c0e6f529eba7acd3bf493767300e5c5dbb
