### ISSUE TITLE
Inventory Display

### ISSUE THREAD

**Issue by BryanBoru** [TFT8/addons#4]
75th Ranger Beret shows a Black (NATO) Beret..

**Comment by BryanBoru** [comment]
I understand the use of a similar beret, but the difference between the 75th and the NATO one makes me think we might want a UI image.

**Comment by theYoursTruly** [comment]
Fixed with https://github.com/TFT8/addons/commit/461d568e1d7e8a136d77f94d7655c4e27b608a90
